### ISSUE TITLE
Paging doesn't work

### ISSUE THREAD

**Issue by Graidenix** [adamspe/odata-resource#3]
**$skip** and **$top** are read from query string, but mongoose query requires only number type.

![screen shot 2016-10-12 at 15 00 18](https://cloud.githubusercontent.com/assets/1109809/19309290/a63c5eaa-908c-11e6-9d9a-91ae09a07298.png)

mongoDB@3.2.7
mongoose@4.5.9
node@6.2.2
npm@3.9.5

**Comment by adamspe** [comment]
Thanks for the fix.  Existing tests didn't catch because of a dev dependency on an older version of mongoose.

Updated dependency to mongoose 4.5.x, bumped version to 0.2.1 and published latest to npm 
https://www.npmjs.com/package/odata-resource

Closing issue.
