### ISSUE TITLE
$expand

### ISSUE THREAD

**Issue by ahbtoplama** [adamspe/odata-resource#5]
Hi

Any of the friends may need master-detail tables on the real time.
Can you and $expand feature on odata-resource ?

**Comment by adamspe** [comment]
I'll look into adding it.  In the meantime, you can use the "populate" property when defining your resource (https://adamspe.github.io/odata-resource/Resource.html).  Though then it will always be there, not only on request.

Doing this requires that your mongoose schema is set up properly.  That is there is a mongoose schema for the included related reference and the "ref" is properly defined on the reference schema itself.

**Comment by adamspe** [comment]
Published version 1.2 with support for $expand.

https://www.npmjs.com/package/odata-resource#new-in-12
